services:
  - type: web
    name: flask-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: YOLO_MODEL_PATH
        value: ../src/best.pt
      - key: UPLOAD_FOLDER
        value: uploads